### ISSUE TITLE
Module not found IONIC

### ISSUE THREAD

**Issue by gyanidude** [zoho/SalesIQ-Mobilisten-Cordova#6] opened 2021-11-01 10:19 UTC
Module not found: Can't resolve 'cordova-zohosalesiq-mobilisten'
import {ZohoSalesIQ} from "cordova-zohosalesiq-mobilisten"; // Error is coming in this line

**Comment by Angu-G** [comment] 2021-11-02 08:01
Hi @gyanidude, Thank you for your patience, Have you tried the following code which we have mentioned in our [installation doc](https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-installation.html).  

![image](https://user-images.githubusercontent.com/58692424/139808047-a26a19c9-76b9-4549-8294-5d2d0b170865.png)

**Comment by gyanidude** [comment] 2021-11-02 08:22
@Angu-G  Yes I have tried this and compilation error goes away but then reference error started to come
![image](https://user-images.githubusercontent.com/24972799/139810751-13f01a98-4516-49bd-9090-574267d8b85c.png)
Just to add more details, I am using IONIC React with Capacitor.

**Comment by gyanidude** [comment] 2021-11-08 06:06
@Angu-G any update?

**Comment by Angu-G** [comment] 2021-11-08 14:54
Hello @gyanidude, Thank you for your patience. We have checked this issue on our end and we couldn't reproduce the same. We suspect that the plugin might not be installed properly. We request you to try executing **`npx cap sync`** or **`ionic prepare`** from your project's root directory and try again.

**Comment by Angu-G** [comment] 2021-11-15 04:16
Hi @gyanidude, We are closing this issue now since it has had no recent updates. As mentioned earlier, we expect the solution provided might be helpful. 
Please feel free to reach us in case you have further queries.
Thanks.

**Closed as completed by Angu-G** 2021-11-15 04:16 UTC
